[package]
name = "srrssr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = "0.12.9"
rss = "2.0.9"
terminal_size = "0.4.0"
tokio = { version = "1.41.1", features = ["full"] }
